#!/bin/bash
#import str
source $UBIN/lib.sh

#SRVFILE=$1
CMD=$1

#dp113 192.168.143.113 22 work work
#0     1               2  3    4
if [ $# -lt 1 ]; then
echo "$0 must have two parameter 
example:
	$0 [server_file] [command] "
	exit;
fi

SRVFILE=$UBIN/servers.dat
#UPPATH=/home/work
#LC_FILENAME=`get_filename $`
#echo "Filename $FILE_NAME"

cat $SRVFILE|while read line
do
        resisempty=`isempty $line`
        if [ "$resisempty" = "true" ]; then
                continue
        fi
        declare -a params=($line)
        echo "IP:${params[1]} PORT:${params[2]} USER:${params[3]} PASS:${params[4]}"
	set -x
	ssh -p ${params[2]} ${params[3]}@${params[1]} $CMD
	set +x
done

